---
- hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
    private_eth: openvpn
    public_eth: ens3
  vars_files:
    - ../{{ config_file }}
  roles:
   - root-password
   - vpn-client
   - ndppd
   - docker
   - firewall
   - sysdig
   - monitoring
